### ISSUE TITLE
How to run test-object-detector file?

### ISSUE THREAD

**Issue by TuanHAnhVN** [bikz05/object-detector#18]
When running "test-object-detector" line in terminal, it's not successful. :(. Error: "test-object-detector: command not found". I changed name to test-object-detector.py to run but not success with error: **_"../data/dataset/CarData.tar.gz: No such file or directory
tar (child): ../data/dataset/CarData.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "../object-detector/extract-features.py", line 5, in <module>
    from sklearn.externals import joblib
ImportError: No module named sklearn.externals
Traceback (most recent call last):
  File "../object-detector/train-classifier.py", line 3, in <module>
    from sklearn.svm import LinearSVC
ImportError: No module named sklearn.svm
Traceback (most recent call last):
  File "../object-detector/test-classifier.py", line 5, in <module>
    from sklearn.externals import joblib
ImportError: No module named sklearn.externals"_**

Help me! thanks

**Comment by arcslash** [comment]
Did you check whether the scikit-learn is installed for python2? 
And download dataset and save in under /data/dataset

**Comment by karlLiuk** [comment]
u should create a directory 'dataset' below data
