### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead:

### ISSUE THREAD

**Issue by deekshithmr95** [bikz05/object-detector#21]
I'm running `test-object-detector.py` on Windows 10 64bit with python 3.6.3 
(added `print `statement's missing parenthesis) 

python successfully downloaded and extracted  'UIUC Image Database for Car Detection'
but i'm getting error [here](https://github.com/bikz05/object-detector/blob/872d519f9e515ab0860b802a157df9b42063f78e/object-detector/train-classifier.py#L42)

> ValueError: Expected 2D array, got 1D array instead:
> array=[].
> Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
> Traceback (most recent call last):

how to resolve this issue?

**Comment by vermouthzjh** [comment]
In `test-classifier.py`, before `pred = clf.predict(fd)`, add `fd = [fd]`.

**Comment by vermouthzjh** [comment]
In `test-classifier.py`, before `pred = clf.predict(fd)`, add `fd = [fd]`.

**Comment by alwansm** [comment]
hello @vermouthzjh  I tried your method now i am getting : 
`Traceback (most recent call last):
  File "test-classifier.py", line 72, in <module>
    pred = clf.predict(fds)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sklearn\linear_model\base.py", line 324, in predict
    scores = self.decision_function(X)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sklearn\linear_model\base.py", line 305, in decision_function
    % (X.shape[1], n_features))
ValueError: X has 10206 features per sample; expecting 35721`

**Comment by DeepInDeeper** [comment]
@alwansm  Hi, I met the same problems.Have u solved it?

**Comment by chenqing** [comment]
The same problem to me

**Comment by LazyG** [comment]
bump

**Comment by HenryJunW** [comment]
Same problem, anyone solve it yet?

**Comment by Tomingz** [comment]
fd=fd.reshape(1,-1)
pred=clf.predict(fd)
It works.
but I have another error:ValueError: X has 22032 features per sample; expecting 38916,how to fix it?

**Comment by fistyee** [comment]
> fd=fd.reshape(1,-1)
> pred=clf.predict(fd)
> It works.
> but I have another error:ValueError: X has 22032 features per sample; expecting 38916,how to fix it?

Same problem,, Do you solved this?
