### ISSUE TITLE
Please anser the problem of numpy error.

### ISSUE THREAD

**Issue by thaingiW** [bikz05/object-detector#29]
classifier = svm.SVC(gamma=0.001)
>>> classifier.fit(data,targets)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 149, in fit
    accept_large_sparse=False)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 747, in check_X_y
    estimator=estimator)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 522, in check_array
    array = np.asarray(array, dtype=object, order=order)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype,copy=False, order=order)
ValueError: setting an array element with a sequence.
How can I solve this error?Thanks in advance!

**Comment by Damini1098** [comment]
Hi thaingiW 
i am also facing this issue . is this issue solved?
if you solve please help me 
thank you in advance
