### ISSUE TITLE
Error During test

### ISSUE THREAD

**Issue by nicolasbolzan** [bikz05/object-detector#8]
Hi!, awesome code.
I'm getting this error during the execution of test-classifier.py:

**Traceback (most recent call last):
  File "test-classifier.py", line 69, in <module>
    pred = clf.predict(fd)
  File "/usr/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 268, in predict
    scores = self.decision_function(X)
  File "/usr/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 249, in decision_function
    % (X.shape[1], n_features))
ValueError: X has 2430 features per sample; expecting 5184**

Is there any correlation with the number of positive and negative samples?

I'm puting 100 Pos images and 13000 Neg images
Resolution: 80X80 

Regards!

**Comment by ghanshyamdudhatrapy** [comment]
Hi nicolasbolzan,
you have to take double negative images then positive images,

if you are take 100 +ve images the you have to take maximum 200 -ve images

May be this tips helps you to resolve your problem

**Comment by swapster** [comment]
Stuck with the same issue.
Took 526 positive and 1052 negative images.

Is there any advices how to fix it?
Thanks.

**Comment by Nakul22** [comment]
Change line 44 from
min_wdw_sz = (100, 40)
to
min_wdw_sz = (64, 64)

This will create equal number of gradient features as in sum model.
